import "../globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import CategoryTab from "./components/CategoryTab";
import FeaturedSidebar from "./components/FeaturedSidebar";
import Providers from "./providers";
import Head from "next/head";
import { Poppins, Roboto_Slab } from "next/font/google";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const roboto_slab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Lassonde Blockchain Blog",
  description: "Generated by LasDevers",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark scroll-smooth">
      <body>
        <main className={poppins.className}>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </main>
      </body>
    </html>
  );
}
